# This file was generated by GoReleaser. DO NOT EDIT.
cask "secretree" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "fb6c91b979a9fa73b48faf992dfff1aaa18a766d75ee884e37d3a2bf63cd54c4"
      url "https://github.com/andraspalinkas/secretree/releases/download/v#{version}/secretree_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4fc921240521f35a68aeb8926677787fa21132738cff0a4a854a82e1546505b0"
      url "https://github.com/andraspalinkas/secretree/releases/download/v#{version}/secretree_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f4c841ba087ccee0a917565b05a115d197c31e5bc1e1db3b0a67a30e692b1cc5"
      url "https://github.com/andraspalinkas/secretree/releases/download/v#{version}/secretree_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7f186a158c506ad99462e4ad1f89c501103e14c257e8d64de7ef1db0e52e349"
      url "https://github.com/andraspalinkas/secretree/releases/download/v#{version}/secretree_#{version}_linux_amd64.tar.gz"
    end
  end

  name "secretree"
  desc "Private git: encrypted repositories on any host, with pull requests, reviews and CI intact"
  homepage "https://secretree.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secretree"

  postflight do
    # the git remote helper is the same binary under a second name
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/secretree", "#{HOMEBREW_PREFIX}/bin/git-remote-secretree"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/git-remote-secretree"
  end

  # No zap stanza required
end
