# This file was generated by GoReleaser. DO NOT EDIT.
cask "secretree" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "223b5e0efd269f9323f8eb4dab5af1ea505ac69e57f1b60180d92e49d622ce43"
      url "https://github.com/andraspalinkas/secretree/releases/download/v#{version}/secretree_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7c0232fb6b55fde12ed08060e59b25fda70ad597bf851fa223a2d76a2162646"
      url "https://github.com/andraspalinkas/secretree/releases/download/v#{version}/secretree_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f9bb94798796396f6f5829fb7f764ed176d8159f9e9ccae2027b8e8390acba4e"
      url "https://github.com/andraspalinkas/secretree/releases/download/v#{version}/secretree_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "87a3ba0dd12b198d03cf2c40481cda1f0bfac00143587572934dc2a07d4169b6"
      url "https://github.com/andraspalinkas/secretree/releases/download/v#{version}/secretree_#{version}_linux_amd64.tar.gz"
    end
  end

  name "secretree"
  desc "Private git: encrypted repositories on any host, with pull requests, reviews and CI intact"
  homepage "https://secretree.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secretree"

  postflight do
    # the git remote helper is the same binary under a second name
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/secretree", "#{HOMEBREW_PREFIX}/bin/git-remote-secretree"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/git-remote-secretree"
  end

  # No zap stanza required
end
