# This file was generated by GoReleaser. DO NOT EDIT.
cask "secretree" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "161316dc9d5f24d7d7e95e72e7e5766c85e0d7f46801f945fea13066dcedf444"
      url "https://github.com/buildsnap-dev/secretree/releases/download/v#{version}/secretree_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "678fb6a23d30a2af41b4e4fc60a5700cca0db72317f71ccfeb5198d8f5159e14"
      url "https://github.com/buildsnap-dev/secretree/releases/download/v#{version}/secretree_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "deff10d9d059f355e7b32bffa1624742ce6535f601a590129276c9db28be3daa"
      url "https://github.com/buildsnap-dev/secretree/releases/download/v#{version}/secretree_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec6a7b01d733dd9f1a085e59705652c64b66b3551dbb226067ba5deaede2efd1"
      url "https://github.com/buildsnap-dev/secretree/releases/download/v#{version}/secretree_#{version}_linux_amd64.tar.gz"
    end
  end

  name "secretree"
  desc "Private git: encrypted repositories on any host, with pull requests, reviews and CI intact"
  homepage "https://secretree.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secretree"

  postflight do
    # the git remote helper is the same binary under a second name
    FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/secretree", "#{HOMEBREW_PREFIX}/bin/git-remote-secretree"
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/git-remote-secretree"
  end

  # No zap stanza required
end
